screen credits_overlay():
    # Semi-transparent background
    frame:
        background Solid("#000000AA")
        xalign 0.5
        yalign 0.5
        xsize 600
        ysize 400
        padding (30, 30)
        
        vbox:
            align (0.5, 0.5)
            spacing 20
            
            text "CREDITS" style "credits_title"
            
            vbox:
                spacing 10
                text "THE END" style "credits_text"
                text "Writer: Yuri Man" style "credits_text"
                text "Artist: Alex Johnson" style "credits_text"
                text "Programmer: Mesastraw (on GitHub)" style "credits_text"
                text "Programmer 2: Yuri Man" style "credits_text"

            
            textbutton "Close":
                xalign 0.5
                action Hide("credits_overlay")

init python:
    style.credits_title = Style(style.default)
    style.credits_title.size = 36
    style.credits_title.color = "#FFFFFF"
    style.credits_title.bold = True
    
    style.credits_text = Style(style.default)
    style.credits_text.size = 24
    style.credits_text.color = "#FFFFFF"

label ending:
    show screen day_screen

    scene black with fade

    show witch at right

    show ys_sprite at left

    witch "Have you made your choice President?"

    pres "Wait, wait, hold on."

    menu: 
        "Why would you want a yuri trope gone?":
            pres "Surely, as an army of Yuri Witches, the sacrifice of a trope would affect your ranks as well?"
            
            witch """
             Well done. I see some semblance of intelligence remains within the bureaucrats.
        	 
             Tell me, Miss President, do you know what Doomed Yuri is?
                """
            pres "No?"
            witch "And Toxic Yuri?"
            pres "What are you talking about??"
            witch "The late president was a fool. An absolute starry eyed fool. She decided that humanity had grown past war and conflict-"
            pres """Yes, yes, 
            
            I know she gutted the armies funding and you guys are still butthurt-
            """
            witch"""Idiot!
	
            Fool!
	
            Do not interrupt me.
	
            If you look into the history of mankind, the magic that we employ is never mentioned. The capability to strike down any foe at any distance, but for some reason it was never deployed in war? Ridiculous is it not?
            """
            pres "T-Thats impossible!"
            witch """Just goes to show how little you know. Our abilities stem from something unique to Yuri itself. The previous era of humanity had no way of knowing about this power, for before Yuristan there had never been such a concentration of pure WLW.
            
            You see, tropes like toxic and doomed yuri hurt people. And that created angst energy, and those of us born into that energy could use it to inflict harm upon whomever we wished. This power allowed for our relatively poor and weak nation to defend its borders and protect its citizens. 

            Over time, man learnt of our abilities and decided attacking us was futile. That was why YaoIsreal withdrew from the rest of the world. It knew that as long as we existed, complete conquest was impossible.

            That was when your naive predecessor came in. She declared military dispute to be a thing of the past, and she defunded the army. But she didn’t stop there. She set out on a decades long quest to wipe pain energy from our very civilization, because for there to be angst energy, there had to be hurt people, and she hated to think of her citizens being hurt. 

            And she succeeded. She undoomed every narrative, and she healed every toxic coupling.
            """
            pres "And without angst energy, you can’t use your powers…"
            witch """Correct. The men are stronger than us, we cannot beat them in physical prowess. And investing into weapon development would take funding from more important sectors, like housing, health, and especially our refugee program.

            Magic kept our borders safe, and our people happy. But if all our people are happy, then we have no magic.
            """
            pres "So you would sacrifice a trope, and use the immense angst generated by that to eradicate YaoIsreal??"
            witch "Yes."
            pres "There has to be another way!"
            witch "There isn't"
            pres "Then you have to be lying! I have the highest security clearance possible! How could you know more than me?!"
            witch """
            You were alive during the last president's time in office. Yet you do not remember doomed or toxic yuri. While that moron managed to wipe angst energy without making use of magic, she knew that as long as the memory of that magic remained, it would always return. But to wipe even the echo of angst energy, that would take magic.

            And for that, you need angst.

            So that dummy created one last doomed narrative. Our narrative. My stupid, idiotic, beautiful wife killed herself, so I could use my own pain to put an end to suffering once and for all. 
            
            She killed herself. For fucking nothing.

            My wife died, and that bastard to the west began plotting as soon as he heard?!
            
            I lost basically everything, but that bitch wants all that remains as well?
            
            He will suffer. He will suffer like none other.

            The simulation should have generated enough attachment between you and the three tropes to create some angst energy. I will use that energy to wipe that trope from existence. And then I will make YaoIsreal pay.

            So choose President.
            """

            jump final_choice

        "I have made my choice.":
            jump final_choice

label final_choice:
    $ made_choice = ""

    menu:
        "Take out all Tsunderes":
            $ made_choice = "Tsundere" 

        "Remove all Girls In Denial":
            $ made_choice = "Girl In Denial"

        "Delete All Derederes":
            $ made_choice = "Derederes"


    hide witch

    show npc at right:
        zoom 0.35
    
    sci "*sniff* Miss president! you're finally awake!"

    pres "What happened? Did it not work? Are we still under attack??"

    sci "N-No we’re safe, YaoIsreal is no more., *sniff*"

    pres "Then why are you crying??"

    sci "I-Its just "
    extend "My wife was a [made_choice]"

    pres "Oh. I'm sorry.."
    extend " Would you like a hug?"

    sci "y-yeah."

    scene hug
        
    Show screen credits_overlay

    return
